server:
  port: 9002

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:user
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/